---
- name: Configure Switch1
  hosts: switch1
  remote_user: cumulus
  become: yes
  become_method: sudo
  tasks:
    - name: Set hostname for Switch1
      command: net add hostname switch1

    - name: Add interfaces to Switch1
      command: net add interface swp1,swp2,swp3,swp4,swp5

    - name: Add bond1 slaves on Switch1
      command: net add bond bond1 bond slaves swp1
    
    - name: Add bond3 slaves on Switch1
      command: net add bond bond3 bond slaves swp3
    
    - name: Add peerlink slaves on Switch1
      command: net add bond peerlink bond slaves swp4,swp5

    - name: Set access VLAN on bond1 on Switch1
      command: net add bond bond1 bridge access 100

    - name: Set access VLAN on bond2 on Switch1
      command: net add bond bond2 bridge access 200     

    - name: Set access VLAN on bond3 on Switch1
      command: net add bond bond3 bridge vids 100,200
    
    - name: Set access VLAN on bond3 on Switch1
      command: net add bond bond3 bridge vids 100,200    
    
    - name: Add peerlink in bridge on Switch1
      command: net add bridge bridge ports peerlink
    
    - name: Configure loopback lo on Switch1
      command: net add loopback lo ip address 10.10.10.1/24

    - name: Add clag_id in bond1 on Switch1
      command: net add bond bond1 clag id 1
    
    - name: Add clag_id in bond2 on Switch1
      command: net add bond bond2 clag id 2

    - name: Add clag_id in bond3 on Switch1
      command: net add bond bond3 clag id 3

    - name: Configure peerlink on Switch1
      command: net add clag peer sys-mac 44:38:39:BE:EF:AA interface swp4-5 primary backup-ip 10.10.10.2

    - name: Apply the changes on Switch1
      command: net pending
      register: output

    - name: Commit the changes on Switch1
      command: net commit
      when: output.stdout != ""

- name: Configure Switch2
  hosts: switch2
  remote_user: cumulus
  become: yes
  become_method: sudo
  tasks:
    - name: Set hostname for Switch1
      command: net add hostname switch1

    - name: Add interfaces to Switch1
      command: net add interface swp1,swp2,swp3,swp4,swp5

    - name: Add bond1 slaves on Switch1
      command: net add bond bond1 bond slaves swp1
    
    - name: Add bond3 slaves on Switch1
      command: net add bond bond3 bond slaves swp3
    
    - name: Add peerlink slaves on Switch1
      command: net add bond peerlink bond slaves swp4,swp5

    - name: Set access VLAN on bond1 on Switch1
      command: net add bond bond1 bridge access 100

    - name: Set access VLAN on bond2 on Switch1
      command: net add bond bond2 bridge access 200     

    - name: Set access VLAN on bond3 on Switch1
      command: net add bond bond3 bridge vids 100,200
    
    - name: Set access VLAN on bond3 on Switch1
      command: net add bond bond3 bridge vids 100,200    
    
    - name: Add peerlink in bridge on Switch1
      command: net add bridge bridge ports peerlink
    
    - name: Configure loopback lo on Switch1
      command: net add loopback lo ip address 10.10.10.1/24

    - name: Add clag_id in bond1 on Switch1
      command: net add bond bond1 clag id 1
    
    - name: Add clag_id in bond2 on Switch1
      command: net add bond bond2 clag id 2

    - name: Add clag_id in bond3 on Switch1
      command: net add bond bond3 clag id 3

    - name: Configure peerlink on Switch1
      command: net add clag peer sys-mac 44:38:39:BE:EF:AA interface swp4-5 primary backup-ip 10.10.10.1

    - name: Apply the changes on Switch1
      command: net pending
      register: output

    - name: Commit the changes on Switch1
      command: net commit
      when: output.stdout != ""


- name: Configure Switch3
  hosts: switch3
  remote_user: cumulus
  become: yes
  become_method: sudo
  tasks:
    - name: Set hostname for Switch3
      command: net add hostname switch3

    - name: Add interfaces to Switch3
      command: net add interface swp1,swp2,swp3

    - name: Set bridge PVID for Switch3
      command: net add bridge bridge pvid 1

    - name: Add trunk VLANs to interfaces on Switch3
      command: net add interface swp1,swp2 bridge trunk vlans 10-20

    - name: Apply the changes on Switch3
      command: net pending
      register: output

    - name: Commit the changes on Switch3
      command: net commit
      when: output.stdout != ""


- name: Configure network interfaces of Machine1
  hosts: Machine1
  become: true
  tasks:
    - name: Configure DHCP on ens33
      ansible.builtin.copy:
        dest: /etc/network/interfaces.d/ens33
        content: |
          allow-hotplug ens33
          iface ens33 inet dhcp
        owner: root
        group: root
        mode: '0644'

    - name: Configure ens34 for bonding
      ansible.builtin.copy:
        dest: /etc/network/interfaces.d/ens34
        content: |
          auto ens34
          iface ens34 inet manual
            bond-master bond0
        owner: root
        group: root
        mode: '0644'

    - name: Configure ens35 for bonding
      ansible.builtin.copy:
        dest: /etc/network/interfaces.d/ens35
        content: |
          auto ens35
          iface ens35 inet manual
            bond-master bond0
        owner: root
        group: root
        mode: '0644'

    - name: Configure bond0 with static IP and bonding parameters
      ansible.builtin.copy:
        dest: /etc/network/interfaces.d/bond0
        content: |
          auto bond0
          iface bond0 inet static
            address 192.168.1.1/24
            gateway 192.168.1.254
            mtu 1500
            bond-mode 802.3ad
            bond-miimon 100
            bond-downdelay 200
            bond-lacp-rate 1
            bond-xmit-hash-policy layer3+4
            bond-slaves ens34 ens35
        owner: root
        group: root
        mode: '0644'

    - name: Restart networking service
      ansible.builtin.service:
        name: networking
        state: restarted

- name: Configure network interfaces of Machine2
  hosts: Machine2
  become: true
  tasks:
    - name: Configure DHCP on ens33
      ansible.builtin.copy:
        dest: /etc/network/interfaces.d/ens33
        content: |
          allow-hotplug ens33
          iface ens33 inet dhcp
        owner: root
        group: root
        mode: '0644'

    - name: Configure ens34 for bonding
      ansible.builtin.copy:
        dest: /etc/network/interfaces.d/ens34
        content: |
          auto ens34
          iface ens34 inet manual
            bond-master bond0
        owner: root
        group: root
        mode: '0644'

    - name: Configure ens35 for bonding
      ansible.builtin.copy:
        dest: /etc/network/interfaces.d/ens35
        content: |
          auto ens35
          iface ens35 inet manual
            bond-master bond0
        owner: root
        group: root
        mode: '0644'

    - name: Configure bond0 with static IP and bonding parameters
      ansible.builtin.copy:
        dest: /etc/network/interfaces.d/bond0
        content: |
          auto bond0
          iface bond0 inet static
            address 192.168.1.1/24
            gateway 192.168.1.254
            mtu 1500
            bond-mode 802.3ad
            bond-miimon 100
            bond-downdelay 200
            bond-lacp-rate 1
            bond-xmit-hash-policy layer3+4
            bond-slaves ens34 ens35
        owner: root
        group: root
        mode: '0644'

    - name: Restart networking service
      ansible.builtin.service:
        name: networking
        state: restarted

